# Generated by Django 6.0.6 on 2026-06-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_profile_address_remove_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(max_length=20),
        ),
    ]
