# Generated by Django 6.0.6 on 2026-06-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_image_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Laptop', max_length=50),
            preserve_default=False,
        ),
    ]
