# Generated by Django 6.0.6 on 2026-07-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_address_latitude_address_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='current_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
